# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: szymon.borucki@gmail.com
  email_provider_password: 9UtyV2yFsbnyTGRhJj
  domain_name: example.com
  mailchimp_api_key: 8e57b7e9c73e525756e0960579ca26c0-us8
  mailchimp_list_id: c1491cf428
  owner_email: szymon.borucki@gmail.com
  secret_key_base: 65988edd2bcc89b3cb2f860c6c319497abbf08be9a261485f73172ee959a410485f808b04101d484647ea43c8833d5e80f45582f25eb1f81e30e08af42072bd1

test:
  secret_key_base: 65988edd2bcc89b3cb2f860c6c319497abbf08be9a261485f73172ee959a410485f808b04101d484647ea43c8833d5e80f45582f25eb1f81e30e08af42072bd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  email_provider_username: szymon.borucki@gmail.com
  email_provider_password: 9UtyV2yFsbnyTGRhJj
  domain_name: example.com
  mailchimp_api_key: 8e57b7e9c73e525756e0960579ca26c0-us8
  mailchimp_list_id: c1491cf428
  owner_email: szymon.borucki@gmail.com
  secret_key_base: 65988edd2bcc89b3cb2f860c6c319497abbf08be9a261485f73172ee959a410485f808b04101d484647ea43c8833d5e80f45582f25eb1f81e30e08af42072bd1